---

# include the different types of servers
- include: syslogservers.yml
- include: dbservers.yml
- include: dbslaveservers.yml
- include: nfsservers.yml
- include: webservers.yml

# - include: pgpoolservers.yml

#- include: lbservers.yml
#- include: regservers.yml
#- include: ldapservers.yml


