---

# include the different types of servers
- include: syslogservers.yml
- include: dbservers.yml
- include: dbslaveservers.yml
- include: nfsservers.yml
- include: webservers.yml
- include: lbservers.yml

# currently, the ldap server install fails
# 15.5.2014, jcf
#- include: ldapservers.yml


