---

- name: Community - Download OwnCloud release
  get_url:
    url=http://download.owncloud.org/community/owncloud-{{ OWNCLOUD_VERSION }}.tar.bz2
    dest=/tmp/owncloud-{{ OWNCLOUD_VERSION }}.tar.bz2
    mode=0644
  tags:
    - app


- name: Community - Unpack OwnCloud
  command: chdir=/var/www tar -xjf /tmp/owncloud-{{ OWNCLOUD_VERSION }}.tar.bz2
  tags:
    - app